"""Add user_type to users

Revision ID: 02079e9ec801
Revises: e361436fabe0
Create Date: 2026-05-15 11:23:04.815941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02079e9ec801'
down_revision: Union[str, None] = 'e361436fabe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add user_type with server default 'user' so existing rows get a value
    op.add_column('users', sa.Column('user_type', sa.String(), server_default=sa.text("'user'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###
