"""Fix: Make user_id not nullable and add created_at to email_otps

Revision ID: e361436fabe0
Revises: c590a88e1344
Create Date: 2026-05-14 16:48:53.723827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e361436fabe0'
down_revision: Union[str, None] = 'c590a88e1344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_otps', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('email_otps', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_otps', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('email_otps', 'created_at')
    # ### end Alembic commands ###
